@echo off
echo Khởi động Hệ sinh thái AgriSmart...

echo 1. Đánh thức AI Engine (Python)...
start "AI Engine (Python)" cmd /k "cd AI_Engine && .venv\Scripts\python.exe main.py"

echo 2. Đánh thức Backend (Java Spring Boot)...
start "Spring Boot (Java)" cmd /k "cd Backend && mvnw.cmd spring-boot:run"

echo 3. Khởi chạy Giao diện App (Flutter Web Preview)...
start "Flutter App" cmd /k "cd my_ai_plant_app && flutter run -d web-server --web-hostname 0.0.0.0 --web-port 5000"

echo Xong! Vui long cho vai giay de cac server khoi dong hoan toan.
