// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCglRzctd1gZ_XixaWzBJWiUrZ8y-C6lzY',
    appId: '1:896398806405:web:3780a39824439810e148ec',
    messagingSenderId: '896398806405',
    projectId: 'floria-71734',
    authDomain: 'floria-71734.firebaseapp.com',
    storageBucket: 'floria-71734.firebasestorage.app',
    measurementId: 'G-KPDX1ZFSW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSDZuKWlB87OEeYGP0BzTJu9eVf9t0DJ0',
    appId: '1:896398806405:android:c57e2b41bb0a4cb8e148ec',
    messagingSenderId: '896398806405',
    projectId: 'floria-71734',
    storageBucket: 'floria-71734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIqOkx6srhJqLrniJj_ywkX6YRFd4KUg',
    appId: '1:896398806405:ios:3b2f4d129a4d7462e148ec',
    messagingSenderId: '896398806405',
    projectId: 'floria-71734',
    storageBucket: 'floria-71734.firebasestorage.app',
    iosClientId: '896398806405-1mm7dtmepc8h6k3snjmo8e9hieeci3n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAiPlantApp',
  );
}
