server.port=8080
# Cau hinh URL cua Python AI Engine
ai.engine.url=http://localhost:8000/predict
# Duong dan den file credentials cua Firebase
firebase.config-path=classpath:serviceAccountKey.json
# Cho phep upload anh lon hon (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
